---
# Update the runner deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
      - name: github-runner
        image: myoung34/github-runner:latest
        env:
        - name: REPO_URL
          value: "https://github.com/misua/workflows"
        - name: RUNNER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-secret
              key: access-token
        - name: RUNNER_WORKDIR
          value: "/tmp/runner/work"
        - name: LABELS
          value: "self-hosted,k8s"
        volumeMounts:
        - name: work
          mountPath: /tmp/runner/work
      volumes:
      - name: work
        emptyDir: {}
