# .github/workflows/build-and-push.yml
name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up BuildKit
      run: |
        # Ensure buildctl is available
        if ! command -v buildctl &> /dev/null; then
          echo "buildctl not found, installing..."
          wget https://github.com/docker/buildx/releases/download/v0.8.2/buildx-v0.8.2.linux-amd64
          chmod +x buildx-v0.8.2.linux-amd64
          mkdir -p ~/.docker/cli-plugins
          mv buildx-v0.8.2.linux-amd64 ~/.docker/cli-plugins/docker-buildx
        fi
        # Point to the BuildKit daemon running in the cluster
        export BUILDKIT_HOST=kube-pod://buildkitd

    - name: Build and push image
      env:
        DOCKER_REGISTRY: your-registry.com
        IMAGE_NAME: your-image-name
        IMAGE_TAG: ${{ github.sha }}
      run: |
        buildctl build \
          --frontend dockerfile.v0 \
          --local context=. \
          --local dockerfile=. \
          --output type=image,name=$DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG,push=true

    - name: Update deployment
      run: |
        # Assuming you have kubectl configured to access your cluster
        kubectl set image deployment/your-deployment your-container=$DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
