---
apiVersion: v1
kind: Pod
metadata:
  name: network-debug
spec:
  containers:
  - name: network-debug
    image: nicolaka/netshoot
    command: 
      - sleep
      - "3600"
  restartPolicy: Never
