name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: welcome msg
          run: echo "my first github actions job"

        - name: checkout code
          uses: actions/checkout@main

        - name: List files
          run: ls

        - name: Read file
          run: cat README.md

          